yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Модель для управления группами."""
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='Ссылка')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группы'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    """Модель для хранения постов."""
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name="posts",
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Сообщение пользователя'
        verbose_name_plural = 'Сообщения пользователей'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    """Модель для хранения комментариев."""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Комментарий пользователя'
        verbose_name_plural = 'Комментарии пользователей'

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписант'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follows'
            )]

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Введите какой нибудь текст'
        )
        self.fields['group'].empty_label = (
            'Выберите группу 🙂'
        )

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': "Текст поста",
            'group': "Группа",
        }
        help_texts = {
            'text': "Текст нового поста",
            'group': "Выбрать группу",
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginate_page


def index(request):
    """Главная страница"""
    template = "posts/index.html"
    post_list = Post.objects.all()
    page_obj = paginate_page(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Страница группы"""
    template = "posts/group_list.html"
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginate_page(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Профайл пользователя"""
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginate_page(request, posts)
    following = (
        request.user.is_authenticated
        and author.following.filter(user=request.user).exists()
    )
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Просмотр записи"""
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Создание поста"""
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    context = {
        'form': form,
    }
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', request.user)
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """Редактирование поста"""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    pagin = paginate_page(request, posts)
    return render(request, 'posts/follow.html', context={'page_obj': pagin})


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    user_follower = Follow.objects.filter(
        author__username=username,
        user=request.user
    )
    user_follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html'%}
{% load thumbnail %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать
                {% else %}
                  Новый пост
                {% endif %}             
              </div>
              <div class="card-body">
              {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
              {% endif %}
              <form method="post" enctype="multipart/form-data">        
              <form method="post" action="
                  {% if is_edit %}
                    {% url 'posts:post_edit' post.pk %}
                  {% else %}
                    {% url 'posts:post_create' %}
                  {% endif %}">
                  {% csrf_token %}
                  {% for field in form %}
                    <div class="form-group row my-3 p-3">
                        <label for="{{ field.id_for_label }}">
                            {{field.label}}

                            {% if field.field.required %}
                            <span class="required text-danger">*</span>
                            {% endif %}
                        </label>
                        {{ field }}

                        {% if field.help_text %}
                        <small
                                id="{{ field.id_for_label }}-help"
                                class="form-text text-muted"
                        >
                            {{ field.help_text|safe }}
                        </small>
                        {% endif %}
                    </div>
                    {%endfor%} 
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
  </body>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}  
  {% include 'posts/includes/switcher.html' %} 
  {% include 'posts/includes/posts.html' %}
  {% include 'posts/includes/paginator.html' %} 
</div> 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
<div class="container py-5">
  {% block header %}
  <h1 class="display-5 fw-bold text-center">{{ group.title }}</h1>
  <h3 class="lead mb-4 text-center">{{ group.description|linebreaks }}</h3>
  {% endblock %}
  {% for post in page_obj %}
<div class="row border rounded mb-4 shadow-sm">
  <div class="col p-4 flex-column">
    <div class="row">
      <div class="col-auto col-md-6">
        Автор:
        <a href="{% url 'posts:profile' post.author %}">{{ post.author.username }}</a> 
        <br>
        <small>Дата публикации: {{ post.pub_date|date:"d E Y" }}</small>
        <br>
        <small>
          Группа:
          {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a> 
          {% endif %}
        </small>
      </div>
    </div>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}      
    <p>{{ post.text|linebreaks }}</p>
    <div class="row">
      <div class="col-auto">
        <a class="btn btn-primary btn-sm" href="{% url 'posts:post_detail' post.pk %}" title="подробная информация">
          <svg class="i-info" viewBox="0 0 32 32" width="24" height="24" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
            <path d="M16 14 L16 23 M16 8 L16 10"></path>
            <circle cx="16" cy="16" r="14"></circle>
          </svg> подробная информация
        </a>
      </div>
    </div>
  </div>
</div>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block content %} 
  {% include 'posts/includes/switcher.html' %} 
  {% cache 20 index_page request.path page_obj.number %} 
  {% include 'posts/includes/posts.html' %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %} 
</div> 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
  {%block content %}
  <main>
  <div class="container py-5">     
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}  
            <li class="list-group-item">
              Группа:
              <a href="{% url 'posts:group_list' post.group.slug %}">
                {{ post.group.title }}
              </a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор:
              <a href="{% url 'posts:profile' post.author %}">{{ post.author.username }}</a> 
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
           </ul>
        </aside>
        <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=False as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>
        {% if post.author == request.user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}"> Редактировать пост </a>
        {% endif %}
        <hr>
        {% include 'posts/includes/comments.html' %}
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
               {% csrf_token %}      
                <div class="form-group mb-2">
                 {{ form.text|addclass:"form-control" }}
               </div>
               <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
           </div>
         </div>
        {% endif %}  
        </article>
    </div> 
    {% include 'posts/includes/paginator.html' %}
  </div>
  </main>
  {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Профиль пользователя {{ post_title}}{% endblock %}

    {%block content %}
    <div class="container py-5">     
      <div class="mb-5">       
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if request.user != author %}
          {% if following %}
            <a
             class="btn btn-lg btn-light"
             href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
           </a>
         {% else %}
           <a
              class="btn btn-lg btn-primary"
             href="{% url 'posts:profile_follow' author.username %}" role="button"
             >
              Подписаться
            </a>
           {% endif %}
        {% endif %}  
        {% for post in page_obj %}   
         <article>
           <ul>
             <li>
               Дата публикации: {{ post.pub_date|date:"d E Y" }}
             </li>
           </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
           <p>{{ post.text|linebreaksbr }}</p>
           <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
          </article>
           {% if post.group %}       
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
           {% endif %}
           <hr>
         </article>
         {% endfor %}
         
         {% if not forloop.last %}<hr>{% endif %}
         {% include 'posts/includes/paginator.html' %}
      </div>
    {% endblock %}               
        